JoseGutierrezMYPER/JoseGutierrezMYPER/Controllers/TrabajadorController.cs
using JoseGutierrezMYPER.Context;
using JoseGutierrezMYPER.Models;
using JoseGutierrezMYPER.Services;
using JoseGutierrezMYPER.Services.Implementations;
using JoseGutierrezMYPER.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Diagnostics;
using System.Linq;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace JoseGutierrezMYPER.Controllers;

public class TrabajadorController : Controller
{
    private ITrabajadorService _trabajadorService;
    private IDepartamentoService _departamentoService;
    private IDistritoService _distritoService;
    private IProvinciaService _provinciaService;
    
    public TrabajadorController(TrabajadoresPruebaDbContext trabajadoresPruebaDbContext)
    {
        _trabajadorService = new TrabajadorService(trabajadoresPruebaDbContext);
        _distritoService = new DistritoService(trabajadoresPruebaDbContext);
        _provinciaService = new ProvinciaService(trabajadoresPruebaDbContext);
        _departamentoService = new DepartamentoService(trabajadoresPruebaDbContext);
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        IEnumerable<Trabajador> trabajadores = await _trabajadorService.Listar();
        IEnumerable<Distrito> distritos = await _distritoService.Listar();
        IEnumerable<Provincia> provincias = await _provinciaService.Listar();
        IEnumerable<Departamento> departamentos = await _departamentoService.Listar();

        return View(trabajadores);
    }

    [HttpGet]
    public async Task<IActionResult> Guardar(int? idDepartamento,int? idProvincia)
    {
        IEnumerable<Departamento> departamentos = await _departamentoService.Listar();

        ViewBag.Departamentos = new SelectList(departamentos, "Id", "Nombre");
        ViewBag.TipoDocumentos = new SelectList(TipoDocumentoStatic.ListaDeCadenas,"Nombre","Nombre");
        return PartialView("Agregar", new Trabajador());
    }




    [HttpPost]
    public async Task<IActionResult> Guardar(Trabajador trabajador)
    {
        try
        {

            Trabajador trabajadorGuardado = await _trabajadorService.Guardar(trabajador);
        }
        catch (Exception ex)
        {
            Debug.WriteLine(ex.Message);
            return RedirectToAction("Index");
        }
        
        return RedirectToAction("Index");

    }

    public async Task<IActionResult> Eliminar(int id)
    {
        var result = await _trabajadorService.Eliminar(id);

        if (!result)
        {
            return Json(new { response = false });
        }
        
        return Json(new { response = true });
    }

    [HttpGet]
    public async Task<IActionResult> Actualizar(int id)
    {
        var trabajadorObtenido = await _trabajadorService.ObtenerPorId(id);

        IEnumerable<Departamento> departamentos = await _departamentoService.Listar();
        IEnumerable<Distrito> distritos = await _distritoService.Listar();
        IEnumerable<Provincia> provincias = await _provinciaService.Listar();


        var groupProvincias = from provincia in provincias
                              group provincia by provincia.DepartamentoId into newGroup
                              orderby newGroup.Key
                              select newGroup;
        List<Provincia> provinciasNewList = new List<Provincia>();

        foreach (var group in groupProvincias)
        {
            foreach (var provincia in group)
            {

                if (provincia.DepartamentoId == trabajadorObtenido.DepartamentoId)
                {
                    provinciasNewList.Add(provincia);
                }
            }
        }


        var groupDistritos = from distrito in distritos
                              group distrito by distrito.ProvinciaId into newGroup
                              orderby newGroup.Key
                              select newGroup;
        List<Distrito> distritosNewList = new List<Distrito>();

        foreach (var group in groupDistritos)
        {
            foreach (var distrito in group)
            {

                if (distrito.ProvinciaId == trabajadorObtenido.ProvinciaId)
                {
                    distritosNewList.Add(distrito);
                }
            }
        }


        ViewBag.Departamentos = new SelectList(departamentos, "Id", "Nombre");
        ViewBag.Distritos = new SelectList(distritosNewList, "Id", "Nombre");
        ViewBag.Provincias = new SelectList(provinciasNewList, "Id", "Nombre");
        ViewBag.TipoDocumentos = new SelectList(TipoDocumentoStatic.ListaDeCadenas, "Nombre", "Nombre");

        if (trabajadorObtenido != null)
        {

            return PartialView("Actualizar", trabajadorObtenido);

        }
        return PartialView("Actualizar",trabajadorObtenido);
    }
    
    [HttpPost]
    public async Task<IActionResult> Actualizar(Trabajador trabajador)
    {
        try
        {
            Debug.WriteLine("CODIGO  " + trabajador.Id);

            Trabajador trabajadorGuardado = await _trabajadorService.Actualizar(trabajador);

        }
        catch (Exception ex)
        {
            Debug.WriteLine(ex.Message);
        }

        return RedirectToAction("Index");
    }
    
    
    [HttpGet]
    public IActionResult Filtrar()
    {
        return Json(new { response = true });
    }



    [HttpGet]
    public async Task<IActionResult> FiltrarDepartamentoProvincia(int idDepartamento = 0,int idProvincia = 0)
    {
        IEnumerable<Departamento> departamentos = await _departamentoService.Listar();

        ViewBag.Departamentos = new SelectList(departamentos, "Id", "Nombre");

        
        if (idDepartamento > 0)
        {
            IEnumerable<Provincia> provincias = await _provinciaService.Listar();

            Debug.WriteLine(provincias.Count());

            var groupProvincias = from provincia in provincias
                                  group provincia by provincia.DepartamentoId into newGroup
                                  orderby newGroup.Key
                                  select newGroup;

            List<Provincia> provinciasNewList = new List<Provincia>();

            foreach (var group in groupProvincias)
            {
                foreach (var provincia in group)
                {
                    
                    if(provincia.DepartamentoId == idDepartamento)
                    {
                        provinciasNewList.Add(provincia);
                    }
                }
            }

            if (idProvincia > 0)
            {
                IEnumerable<Distrito> distritos = await _distritoService.Listar();

                var groupDistritos = from distrito in distritos
                                     group distrito by distrito.ProvinciaId into newGroup
                                      orderby newGroup.Key
                                      select newGroup;

                List<Distrito> distritosNewList = new List<Distrito>();

                foreach (var group in groupDistritos)
                {
                    foreach (var distrito in group)
                    {
                        if (distrito.ProvinciaId == idProvincia)
                        {
                            distritosNewList.Add(distrito);
                        }
                    }
                }

                ViewBag.Departamentos = new SelectList(departamentos, "Id", "Nombre", idDepartamento);
                ViewBag.Provincias = new SelectList(provinciasNewList, "Id", "Nombre",idProvincia);
                ViewBag.Distritos = new SelectList(distritosNewList, "Id", "Nombre");

                return Json(new { response = ViewBag.Distritos });

            }

            ViewBag.Departamentos = new SelectList(departamentos, "Id", "Nombre",idDepartamento);
            ViewBag.Provincias = new SelectList(provinciasNewList.AsEnumerable(), "Id", "Nombre");

            return Json(new { response = ViewBag.Provincias });
        }


        return Json(new { response = ViewBag.Departamentos });
    }

}

JoseGutierrezMYPER/JoseGutierrezMYPER/Views/Trabajador/Actualizar.cshtml
@model JoseGutierrezMYPER.Models.Trabajador


<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="actualizarModalLabel">Modal title</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">

            <h3>Actualizar</h3>
            <br />
            <hr />
            <div class="row">
                <div class="col-md-4">
                    <form asp-action="Actualizar">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group" style="display:none;">
                            <label asp-for="Id" class="control-label"></label>
                            <input asp-for="Id" class="form-control" />
                            <span asp-validation-for="Id" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="TipoDocumento" class="control-label"></label>
                            <br />
                            <select class="form-control" asp-for="TipoDocumento" asp-items="@((SelectList)ViewBag.TipoDocumentos)">
                            </select>
                            <span asp-validation-for="TipoDocumento" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="NumeroDocumento" class="control-label"></label>
                            <input asp-for="NumeroDocumento" class="form-control" />
                            <span asp-validation-for="NumeroDocumento" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Nombres" class="control-label"></label>
                            <input asp-for="Nombres" class="form-control" />
                            <span asp-validation-for="Nombres" class="text-danger"></span>
                        </div>
                        <div class="form-group ">
                            <label asp-for="Sexo" class="control-label"></label>
                            <br />
                            <div>
                                @Html.RadioButtonFor(model => model.Sexo, "M")Masculino<br />

                            </div>
                            <div>
                                @Html.RadioButtonFor(model => model.Sexo, "F") Femenino<br />
                            </div>
                            <span asp-validation-for="Sexo" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Departamento" class="control-label"></label>
                            <br />
                            @*@Html.DropDownList("TiposProductosList", (SelectList)ViewBag.TipoProducto)*@
                            <select id="departamentosList" class="form-control" asp-for="DepartamentoId" asp-items="@((SelectList)ViewBag.Departamentos)">
                            </select>
                            <span asp-validation-for="DepartamentoId" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Provincia" class="control-label"></label>
                            <br />
                            @*@Html.DropDownList("TiposProductosList", (SelectList)ViewBag.TipoProducto)*@
                            <select id="provinciasList" class="form-control" asp-for="ProvinciaId" asp-items="@((SelectList)ViewBag.Provincias)">
                            </select>
                            <span asp-validation-for="ProvinciaId" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Distrito" class="control-label"></label>
                            <br />
                            @*@Html.DropDownList("TiposProductosList", (SelectList)ViewBag.TipoProducto)*@
                            <select id="distritosList" class="form-control" asp-for="DistritoId" asp-items="@((SelectList)ViewBag.Distritos)">
                            </select>
                            <span asp-validation-for="DistritoId" class="text-danger"></span>
                        </div>
                        <br />
                        <div class="form-group">
                            <input type="submit" value="Actualizar" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>
</div>

JoseGutierrezMYPER/JoseGutierrezMYPER/Views/Trabajador/Agregar.cshtml
@model JoseGutierrezMYPER.Models.Trabajador


<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">

            <h3>Agregar Producto</h3>
            <br />
            <hr />
            <div class="row">
                <div class="col-md-4">
                    <form asp-action="Guardar">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <div class="form-group">
                            <label asp-for="TipoDocumento" class="control-label"></label>
                            <br />
                            <select  class="form-control" asp-for="TipoDocumento" asp-items="@((SelectList)ViewBag.TipoDocumentos)">
                            </select>
                            <span asp-validation-for="TipoDocumento" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="NumeroDocumento" class="control-label"></label>
                            <input asp-for="NumeroDocumento" class="form-control" />
                            <span asp-validation-for="NumeroDocumento" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Nombres" class="control-label"></label>
                            <input asp-for="Nombres" class="form-control" />
                            <span asp-validation-for="Nombres" class="text-danger"></span>
                        </div>
                        <div class="form-group ">
                            <label asp-for="Sexo" class="control-label"></label>
                            <br />
                            <div >
                                @Html.RadioButtonFor(model => model.Sexo, "M") Masculino<br />
                               
                            </div>
                            <div >
                                @Html.RadioButtonFor(model => model.Sexo, "F") Femenino<br />
                            </div>
                            <span asp-validation-for="Sexo" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Departamento" class="control-label"></label>
                            <br />
                            @*@Html.DropDownList("TiposProductosList", (SelectList)ViewBag.TipoProducto)*@
                            <select id="departamentosList" class="form-control" asp-for="DepartamentoId" asp-items="@((SelectList)ViewBag.Departamentos)">
                            </select>
                            <span asp-validation-for="DepartamentoId" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Provincia" class="control-label"></label>
                            <br />
                            @*@Html.DropDownList("TiposProductosList", (SelectList)ViewBag.TipoProducto)*@
                            <select id="provinciasList" class="form-control" asp-for="ProvinciaId" asp-items="@((SelectList)ViewBag.Provincias)">
                            </select>
                            <span asp-validation-for="ProvinciaId" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Distrito" class="control-label"></label>
                            <br />
                            @*@Html.DropDownList("TiposProductosList", (SelectList)ViewBag.TipoProducto)*@
                            <select id="distritosList" class="form-control" asp-for="DistritoId" asp-items="@((SelectList)ViewBag.Distritos)">
                            </select>
                            <span asp-validation-for="DistritoId" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>
</div>

JoseGutierrezMYPER/JoseGutierrezMYPER/Views/Trabajador/AgregarPartial.cshtml
@model JoseGutierrezMYPER.Models.Trabajador

@{
    ViewData["Title"] = "AgregarStockProducto";
}

<h3>Agregar Producto</h3>
<br />
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AgregarStockProducto">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="TipoDocumento" class="control-label"></label>
                <br />
                @*@Html.DropDownList("TiposProductosList", (SelectList)ViewBag.TipoProducto)*@
                <select id="drpEmpList" class="form-control" asp-for="TipoDocumento" asp-items="@((SelectList)ViewBag.TipoProducto)">
                </select>
                <span asp-validation-for="TipoDocumento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumeroDocumento" class="control-label"></label>
                <input asp-for="NumeroDocumento" class="form-control" />
                <span asp-validation-for="NumeroDocumento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombres" class="control-label"></label>
                <input asp-for="Nombres" class="form-control" />
                <span asp-validation-for="Nombres" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sexo" class="control-label"></label>
                <input asp-for="Sexo" class="form-control" />
                <span asp-validation-for="Sexo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Departamento" class="control-label"></label>
                <br />
                @*@Html.DropDownList("TiposProductosList", (SelectList)ViewBag.TipoProducto)*@
                <select id="drpEmpList" class="form-control" asp-for="Departamento" asp-items="@((SelectList)ViewBag.TipoProducto)">
                </select>
                <span asp-validation-for="Departamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Provincia" class="control-label"></label>
                <br />
                @*@Html.DropDownList("TiposProductosList", (SelectList)ViewBag.TipoProducto)*@
                <select id="drpEmpList" class="form-control" asp-for="Provincia" asp-items="@((SelectList)ViewBag.TipoProducto)">
                </select>
                <span asp-validation-for="Provincia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Distrito" class="control-label"></label>
                <br />
                @*@Html.DropDownList("TiposProductosList", (SelectList)ViewBag.TipoProducto)*@
                <select id="drpEmpList" class="form-control" asp-for="Distrito" asp-items="@((SelectList)ViewBag.TipoProducto)">
                </select>
                <span asp-validation-for="Distrito" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-dark" style="margin-top:8px;" asp-action="MantenimientoStockProducto">Regresar a lista</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

JoseGutierrezMYPER/JoseGutierrezMYPER/Views/Trabajador/Index.cshtml
@model IEnumerable<Trabajador>

@{
    ViewData["Title"] = "Lista de Trabajadores";
}


<div id="main-container" class="main-container">
    <div id="container-trabajadores-id" class="container-trabajadores">

        <h1 class="title_list">Trabajadores</h1>
        <div class="button-active-create-container">
            <button id="agregar" type="button" class="btn btn-secondary">Nuevo Registro</button>
        </div>

        <table class="table table-trabajadores">
            <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.TipoDocumento)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NumeroDocumento)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nombres)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Sexo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DepartamentoId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ProvinciaId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DistritoId)
                </th>
                <th>Acciones</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.TipoDocumento)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NumeroDocumento)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombres)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Sexo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Departamento.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Provincia.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Distrito.Nombre)
                    </td>
                    <td>
                        <button type="button" class="actualizar" value="@item.Id" class="button-active-update" >Actualizar</button>
                        <button>Eliminar</button>
                    </td>

                </tr>
            }
            </tbody>
        </table>
    </div>
    <div id="empty-layout">
    </div>
</div>


@section Scripts
{
    <script>


        $(function () {
            $(".actualizar").on("click", function (event) {
                event.preventDefault();
                var value = $(this).val();
                console.log(value)
                $.ajax(
                    {
                        url: "@Url.Action("Actualizar", "Trabajador")",
                        data: {"id":parseInt(value)},
                        type: "get",
                        success: function (response) {
                            $("#modalActualizar").html(response);
                            $("#modalActualizar").modal("show");


                            $("#departamentosList").change(function () {

                                let val = $('#departamentosList option:selected').val();
                                firstFunctionFilterUpdate(val);

                            });

                        },
                        error: function (err, error) {
                            alert(error);
                        }
                    }
                );

            });
        });
        $(function () {
            $("#agregar").on("click", function (event) {
                event.preventDefault();

                $.ajax(
                    {
                        url: "@Url.Action("Guardar", "Trabajador")",
                        type: "get",
                        success: function (response) {
                            $("#modalAgregar").html(response);
                            $("#modalAgregar").modal("show");
                            

                            $("#departamentosList").change(function () {

                                let val = $('#departamentosList option:selected').val();
                                firstFunctionFilterSave(val);
                            });
                            
                        },
                        error: function (err, error) {
                            alert(error);
                        }
                    }
                );

            });
        });

        function firstFunctionFilterSave(val) {
            $.ajax(
                {
                    url: '@Url.Action("FiltrarDepartamentoProvincia", "Trabajador")',
                    data: { "idDepartamento" : parseInt(val)},
                    type: "get",
                    contentType: "application/json; charset=utf-8",
                    success: function (response) {
                        var sel = $("#provinciasList");

                        sel.empty();
                        for (var i = 0; i < response.response.length; i++) {
                            sel.append('<option value="' + response.response[i].value + '">' + response.response[i].text + '</option>');
                        }
                        $("#provinciasList").change(function () {
                            valProvincia = $('#provinciasList option:selected').val()
                            secondFunctionFilterSave(val, valProvincia)
                        });


                    },
                    error: function (err, error) {
                        alert(error);
                    }
                }
            );
        }

        function secondFunctionFilterSave(val, valProvincia) {
            $.ajax(
                {
                    url: '@Url.Action("FiltrarDepartamentoProvincia", "Trabajador")',
                    data: { "idDepartamento": parseInt(val),"idProvincia":parseInt(valProvincia) },
                    type: "get",
                    contentType: "application/json; charset=utf-8",
                    success: function (response) {
                        var sel = $("#distritosList");

                        sel.empty();
                        for (var i = 0; i < response.response.length; i++) {
                            sel.append('<option value="' + response.response[i].value + '">' + response.response[i].text + '</option>');
                        }
                    },
                    error: function (err, error) {
                        alert(error);
                    }
                }
            );
        }



        function firstFunctionFilterUpdate(val) {
            $.ajax(
                {
                    url: '@Url.Action("FiltrarDepartamentoProvincia", "Trabajador")',
                    data: { "idDepartamento": parseInt(val) },
                    type: "get",
                    contentType: "application/json; charset=utf-8",
                    success: function (response) {
                        var sel = $("#provinciasList");

                        sel.empty();
                        for (var i = 0; i < response.response.length; i++) {
                            sel.append('<option value="' + response.response[i].value + '">' + response.response[i].text + '</option>');
                        }
                        $("#provinciasList").change(function () {
                            valProvincia = $('#provinciasList option:selected').val()
                            secondFunctionFilterUpdate(val, valProvincia)
                        }); 


                    },
                    error: function (err, error) {
                        alert(error);
                    }
                }
            );
        }

        function secondFunctionFilterUpdate(val, valProvincia) {
            $.ajax(
                {
                    url: '@Url.Action("FiltrarDepartamentoProvincia", "Trabajador")',
                    data: { "idDepartamento": parseInt(val), "idProvincia": parseInt(valProvincia) },
                    type: "get",
                    contentType: "application/json; charset=utf-8",
                    success: function (response) {
                        var sel = $("#distritosList");

                        sel.empty();
                        for (var i = 0; i < response.response.length; i++) {
                            sel.append('<option value="' + response.response[i].value + '">' + response.response[i].text + '</option>');
                        }
                    },
                    error: function (err, error) {
                        alert(error);
                    }
                }
            );
        }
    </script>
}


<!-- Modal Agregar -->
<div class="modal fade" id="modalAgregar" role="dialog">

</div>


<!-- Modal Actualizar -->
<div class="modal fade" id="modalActualizar" role="dialog">
    
</div>